config/routes.rb
Rails.application.routes.draw do

  get '/store', to: 'store#index'

  get '/store', to: 'store#show'

  devise_for :users

  resources :blogs do
	  resources :reviews
	  get 'page/:page', :action => :index, :on => :collection
  end

  resources :articles do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :products do
    resources :comments
    get 'page/:page', :action => :index, :on => :collection
  end

  root 'page#index'

  get '/about_us', to: 'page#about_us', as: 'about_us'

  get '/contact_us', to: 'page#contact_us', as: 'contact_us'

  get '/products', to: 'page#products'

  get '/newsletter', to: 'page#newsletter', as: 'newsletter'

  get '/calendar(/:year(/:month))', to: 'page#calendar', as: 'calendar'

  get '/articles', to: 'page#articles'

  get '/login', to: 'page#login', as: 'login'

  get 'products/products_email/:id', :controller => :products,  :action => :products_email, as: 'products_email'

  get 'articles/articles_email/:id', :controller => :articles,  :action => :articles_email, as: 'articles_email'

  post '/contact_us', to: 'page#contact_us'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	validates_presence_of :title, :published_date, :author, :content
	has_many :reviews, :dependent => :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  respond_to :html

  def index
	page = params[:page].to_i
	@blogs = Blog.page( page ).per(5)
  end

  def show

  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.save
    respond_with(@blog)
  end

  def update
    @blog.update(blog_params)
    respond_with(@blog)
  end

  def destroy
    @blog.destroy
    respond_with(@blog)
  end

  private
    def set_blog
      @blog = Blog.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :published_date, :author, :content)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :published_date %><br>
    <%= f.date_select :published_date %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>
<%= paginate @blogs %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Published date</th>
      <th>Author</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.published_date %></td>
        <td><%= blog.author %></td>
        <td><%= truncate(blog.content, :escape => false) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @blogs %>
<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<% if @blog.reviews.average(:rating) != nil %>
    <p>
      <strong>Average Rating: </strong><%= (image_tag( 'star.jpg', height: '15', width: '15') * @blog.reviews.average(:rating)).html_safe %>
    </p>
<% else %>
    <p>
      <strong>Average Rating:</strong>
    </p>
<% end %>
<p>
  <strong>Published date:</strong>
  <%= @blog.published_date %>
</p>

<p>
  <strong>Author:</strong>
  <%= @blog.author %>
</p>

<p>
  <%= @blog.content.html_safe %>
</p>
<% if current_user.try(:admin?) %>
    <%= link_to 'Edit', edit_blog_path(@blog) %> |
<% end %>
<%= link_to 'Back', blogs_path %>

<div id="comment">
  <% @blog.reviews.each do |review| %>
      <p>
        <%= image_tag(review.thumbnail) %>
      </p>
      <p>
        <%= review.author %>
      </p>
      <p>
        <%= review.opinion %>
      </p>
      <%= (image_tag( 'star.jpg', height: '15', width: '15') * review.rating).html_safe %> <br />
      <% if current_user.try(:admin?) %>
          <%= link_to 'Remove', blog_review_path(@blog, review), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      <hr>
  <% end %>
  <%= form_for([@blog, @blog.reviews.build]) do |f| %>
      <%= f.hidden_field :blog_id %>
      <div class="field">
        <%= f.label :author %><br>
        <%= f.text_field :author %>
      </div>
      <div class="field">
        <%= f.label :opinion %><br>
        <%= f.text_area :opinion %>
      </div>
      <div class="field">
        <%= f.label :rating %><br>
        <%= f.select :rating, options_for_select(1..5) %>
      </div>
      <div class="field">
        <%= f.label :thumbnail %><br>
        <%= f.text_field :thumbnail %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
  <% end %>
</div>