config/routes.rb
Rails.application.routes.draw do

  get '/store', to: 'store#index'

  get '/store', to: 'store#show'

  devise_for :users

  resources :blogs do
	  resources :reviews
	  get 'page/:page', :action => :index, :on => :collection
  end

  resources :articles do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :products do
    resources :comments
    get 'page/:page', :action => :index, :on => :collection
  end

  root 'page#index'

  get '/about_us', to: 'page#about_us', as: 'about_us'

  get '/contact_us', to: 'page#contact_us', as: 'contact_us'

  get '/products', to: 'page#products'

  get '/newsletter', to: 'page#newsletter', as: 'newsletter'

  get '/calendar(/:year(/:month))', to: 'page#calendar', as: 'calendar'

  get '/articles', to: 'page#articles'

  get '/login', to: 'page#login', as: 'login'

  get 'products/products_email/:id', :controller => :products,  :action => :products_email, as: 'products_email'

  get 'articles/articles_email/:id', :controller => :articles,  :action => :articles_email, as: 'articles_email'

  post '/contact_us', to: 'page#contact_us'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:show, :edit, :update, :destroy, :articles_email]
	before_action :authenticate_user!, except: [:index]

	def articles_email
		User.all.each do |user|
			UserMailer.article_email( @article.title, @article.author, @article.published_date, @article.content, @article.thumbnail, user).deliver
			UserMailer.article_text_email( @article.title, @article.author, @article.published_date, @article.content, @article.thumbnail, user).deliver
		end
		redirect_to(articles_path, :notice => 'E-mail sent successfully')
	end

	# GET /articles
	# GET /articles.json
	def index
		page = params[:page].to_i
		@articles = Article.order(published_date: :desc).page(page).per(5)
	end

	# GET /articles/1
	# GET /articles/1.json
	def show
	end

	# GET /articles/new
	def new
		@article = Article.new
		@commited = params[:commit]
	end

	# GET /articles/1/edit
	def edit

	end

	# POST /articles
	# POST /articles.json
	def create
		@article = Article.new(article_params)

		respond_to do |format|
			if @article.save
				format.html { redirect_to @article, notice: 'Article was successfully created.' }
				format.json { render :show, status: :created, location: @article }
			else
				format.html { render :new }
				format.json { render json: @article.errors, status: :unprocessable_entity }
			end
		end
		User.find_by_newsletter(true).email do |user|
			if @article.published
				UserMailer.article_email(@article.title, @article.author, @article.published_date, @article.content, @article.thumbnail, user).deliver
				redirect_to(articles_path, :notice => 'E-mail sent successfully')
			end
		end
	end

	# PATCH/PUT /articles/1
	# PATCH/PUT /articles/1.json
	def update
		respond_to do |format|
			if @article.update(article_params)
				format.html { redirect_to @article, notice: 'Article was successfully updated.' }
				format.json { render :show, status: :ok, location: @article }
			else
				format.html { render :edit }
				format.json { render json: @article.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /articles/1
	# DELETE /articles/1.json
	def destroy
		@article.destroy
		respond_to do |format|
			format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_article
		@article = Article.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def article_params
		params.require(:article).permit(:title, :author, :published_date, :published, :content, :thumbnail)
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@article.errors.count, 'error') %> prohibited this article from being saved:</h2>

          <ul>
            <% @article.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :author %><br>
      <%= f.text_field :author %>
    </div>
    <div class="field">
      <%= f.label :published_date %><br>
      <%= f.date_select :published_date %>
    </div>
    <div class="field">
      <%= f.label :published %><br>
      <%= f.check_box :published %>
    </div>
    <div class="field">
      <%= tinymce %>
      <%= f.label :content %><br>
      <%= f.text_area :content, :class => 'tinymce', :rows => 10, :cols => 120 %>
    </div>
    <div class="field">
      <%= f.label :thumbnail %><br>
      <%= f.text_field :thumbnail %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<div class="table_div">
<%= paginate @articles %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Published date</th>
      <th>Published</th>
      <th>Content</th>
      <th>Thumbnail</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.author %></td>
        <td><%= article.published_date %></td>
        <td><%= article.published %></td>
        <td><%= truncate(article.content, :escape => false) %></td>
        <td><%= image_tag(article.thumbnail) %></td>
        <td><%= link_to 'Show', article %></td>
        <% if current_user.try(:admin?)%>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
            <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <td><%= link_to 'E-mail Article', articles_email_path(article.id) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @articles %>
<% if current_user.try(:admin?)%>
    <%= link_to 'New Article', new_article_path %>
<% end %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag(@article.thumbnail) %>
</p>

<h1><%= @article.title %></h1>

<p class="center">
  by: <%= @article.author %>
</p>

<p class="center">
  <%= @article.published_date %>
</p>

<p>
  <strong>Published:</strong>
  <%= @article.published %>
</p>

<p>
  <%= @article.content.html_safe %>
</p>
<% if current_user.try(:admin?) %>
    <%= link_to 'Edit', edit_article_path(@article) %> |
<% end %>
<%= link_to 'Back', articles_path %>