config/routes.rb
Rails.application.routes.draw do

  get '/store', to: 'store#index'

  get '/store', to: 'store#show'

  devise_for :users

  resources :blogs do
	  resources :reviews
	  get 'page/:page', :action => :index, :on => :collection
  end

  resources :articles do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :products do
    resources :comments
    get 'page/:page', :action => :index, :on => :collection
  end

  root 'page#index'

  get '/about_us', to: 'page#about_us', as: 'about_us'

  get '/contact_us', to: 'page#contact_us', as: 'contact_us'

  get '/products', to: 'page#products'

  get '/newsletter', to: 'page#newsletter', as: 'newsletter'

  get '/calendar(/:year(/:month))', to: 'page#calendar', as: 'calendar'

  get '/articles', to: 'page#articles'

  get '/login', to: 'page#login', as: 'login'

  get 'products/products_email/:id', :controller => :products,  :action => :products_email, as: 'products_email'

  get 'articles/articles_email/:id', :controller => :articles,  :action => :articles_email, as: 'articles_email'

  post '/contact_us', to: 'page#contact_us'

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates_presence_of :name, :description, :quantity, :selling_price, :cost_of_products, :weight, :thumbnail, :full_image
  has_many :comments, :dependent => :destroy
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :products_email]
  before_action :authenticate_user!

  def products_email
    User.all.each do |user|
      UserMailer.product_email( @product, user ).deliver
redirect_to(products_path, :notice => 'E-mail sent successfuly')
    end
  end

  # GET /products
  # GET /products.json
  def index
    page = params[:page].to_i
    @products = Product.page( page ).per(5)
  end

  # GET /products/1
  # GET /products/1.json
  def show

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :quantity, :selling_price, :cost_of_products, :weight, :thumbnail, :full_image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, 'error') %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= tinymce %>
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => 'tinymce', :rows => 10, :cols => 120 %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :selling_price %><br>
    <%= f.text_field :selling_price %>
  </div>
  <div class="field">
    <%= f.label :cost_of_products %><br>
    <%= f.text_field :cost_of_products %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :thumbnail %><br>
    <%= f.text_field :thumbnail %>
  </div>
  <div class="field">
    <%= f.label :full_image %><br>
    <%= f.text_field :full_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>
<div class="table_div">
<%= paginate @products %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Quantity</th>
      <th>Selling price</th>
      <th>Cost of products</th>
      <th>Weight</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= truncate(product.description, :escape => false) %></td>
        <td class="qty"><%= product.quantity %></td>
        <td><%= number_to_currency(product.selling_price) %></td>
        <td><%= number_to_currency(product.cost_of_products) %></td>
        <td><%= product.weight %> lb.</td>
        <td><%= image_tag(product.thumbnail) %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'E-mail Product', products_email_path(product.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @products %>
<%= link_to 'New Product', new_product_path %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div id="rightcol">
  <p id="name">
    <strong><%= @product.name %></strong>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= @product.quantity %>
  </p>

  <p>
    <strong>Selling price:</strong>
    $<%= @product.selling_price %>
  </p>
  <% if @product.comments.average(:rating) != nil %>
      <p>
        <strong>Average Rating: </strong><%= (image_tag( 'star.jpg', height: '15', width: '15') * @product.comments.average(:rating)).html_safe %>
      </p>
  <% else %>
      <p>
        <strong>Average Rating:</strong>
      </p>
  <% end %>
  <% if current_user.try(:admin?) %>
      <p>
        <strong>Cost of products:</strong>
        <%= @product.cost_of_products %>
      </p>
  <% end %>

  <p>
    <strong>Weight:</strong>
    <%= @product.weight %> lb.
  </p>

  <p>
    <%= @product.description.html_safe %>
  </p>

  <% if current_user.try(:admin?) %>
    <%= link_to 'Edit', edit_product_path(@product) %> |
  <% end %>
  <%= link_to 'Back', products_path %>
</div>

<div id="leftcol">
  <p id="full_image">
    <%= image_tag(@product.full_image) %>
  </p>
</div>

<div id="comment">
<% @product.comments.each do |comment| %>
    <p>
      <%= comment.author %>
    </p>
    <p>
      <%= comment.opinion %>
    </p>
    <%= (image_tag( 'star.jpg', height: '15', width: '15') * comment.rating).html_safe %> <br />
    <% if current_user.try(:admin?) %>
        <%= link_to 'Remove', product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    <hr>
<% end %>
<%= form_for([@product, @product.comments.build]) do |f| %>
    <%= f.hidden_field :product_id %>
    <div class="field">
      <%= f.label :author %><br>
      <%= f.text_field :author %>
    </div>
    <div class="field">
      <%= f.label :opinion %><br>
      <%= f.text_area :opinion %>
    </div>
    <div class="field">
      <%= f.label :rating %><br>
      <%= f.select :rating, options_for_select(1..5) %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>
</div>